General:
    TOKEN: ""
    ACTIVITY: "watching"
    DOING_ACTIVITY: "Tickets"
    STREAMING_ACTIVITY_TWITCH_URL: ""
    STATUS: "online"

    EMBED_COLOR: "#9C27B0"

    GUILD_ID: 1131428235834564669

Tickets:
    ADDED_ROLES: [1131428836488269984]
    ENGLISH_TICKET_CATEGORY_ID: 1131452795631976468
    SPANISH_TICKET_CATEGORY_ID: 1131812349628645516
